//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1008
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpIRC.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpIRC.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {\rtf1\ansi\ansicpg1252\deff0\deflang1031{\fonttbl{\f0\fnil\fcharset0 Calibri;}}
        ///{\*\generator Msftedit 5.41.21.2510;}\viewkind4\uc1\pard\sa200\sl276\slmult1\qc\lang7\ul\b\f0\fs36\par
        ///\par
        ///BCIRC \par
        ///- Helpfile -\par
        ///\par
        ///\pard\sa200\sl276\slmult1\ulnone\b0\fs22 1.0\par
        ///How to use the program.\par
        ///Basically you have to have some stuff installed first before you can even start this program.\par
        ///To start the BCIRC GUI you have to install the following frameworks:\par
        ///- .NET Framework 4.0 or newer \p [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string BCIRC_Help {
            get {
                return ResourceManager.GetString("BCIRC_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die    _____ _                        _____ _____   _____                   
        ///  / ____| |                      |_   _|  __ \ / ____|                  
        /// | (___ | |__   __ _ _ __ _ __     | | | |__) | |                       
        ///  \___ \| &apos;_ \ / _` | &apos;__| &apos;_ \    | | |  _  /| |                       
        ///  ____) | | | | (_| | |  | |_) |  _| |_| | \ \| |____                   
        /// |_____/|_| |_|\__,_|_|  | .__/  |_____|_|  \_\\_____|                  
        ///  _             ____     | |           _                       _     [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Connected {
            get {
                return ResourceManager.GetStream("Connected", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Disconnect {
            get {
                return ResourceManager.GetStream("Disconnect", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream NewMessage {
            get {
                return ResourceManager.GetStream("NewMessage", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PM {
            get {
                return ResourceManager.GetStream("PM", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream UserJoin {
            get {
                return ResourceManager.GetStream("UserJoin", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream UserLeft {
            get {
                return ResourceManager.GetStream("UserLeft", resourceCulture);
            }
        }
    }
}
